server.port=8084
spring.application.name=my-big-number-web

# Thymeleaf Configuration
spring.thymeleaf.cache=false
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8

# Jackson Configuration
spring.jackson.deserialization.fail-on-unknown-properties=true